---
- name: Execute MySQL Query
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Install community.mysql collection (if not installed)
      ansible.builtin.ansible_galaxy:
        name: community.mysql
        state: present

    - name: Ensure required Python library (PyMySQL) is installed
      ansible.builtin.pip:
        name: pymysql
        state: present

  tasks:
    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        database: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

    - name: Print the query result
      debug:
        var: query_result.results
