---
- name: Execute MySQL Query
  hosts: all
  tasks:
    - name: Execute MySQL query
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        database: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

    - name: Print the query result
      debug:
        var: query_result.results
