---
- name: Execute MySQL Query on All Hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result
      ignore_errors: yes

    - name: Store query result in hostvars
      set_fact:
        query_result_for_aggregation: "{{ query_result.query_result }}"
      when: query_result is defined and query_result.query_result is defined

- name: Aggregate Results on Localhost
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Combine results from reachable hosts
      set_fact:
        aggregated_results: >-
          {{
            groups['all']
            | map('extract', hostvars, 'query_result_for_aggregation')
            | select('defined')  # Ignore undefined results
            | list
          }}

    - name: Print aggregated results
      debug:
        var: aggregated_results
