# ---
# - name: Execute MySQL Query
#   hosts: all
#   gather_facts: false

#   tasks:
#     - name: Execute MySQL query
#       community.mysql.mysql_query:
#         login_user: "{{ mysql_user }}"
#         login_password: "{{ mysql_password }}"
#         login_host: "{{ mysql_host }}"
#         login_db: "{{ mysql_database }}"
#         query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
#       register: query_result

#     - name: Print the query result
#       debug:
#         var: query_result.query_result

---
- name: Execute MySQL Query
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

    - name: Add query result to group results
      add_host:
        name: aggregated_results_group
        query_result: "{{ query_result.query_result }}"

- name: Aggregate and print results
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Aggregate results from all hosts
      set_fact:
        all_results: "{{ hostvars | dict2items | selectattr('key', 'search', 'aggregated_results_group') | map(attribute='value.query_result') | list }}"

    - name: Print aggregated results
      debug:
        var: all_results
