# ---
# - name: Execute MySQL Query
#   hosts: all
#   gather_facts: false

#   tasks:
#     - name: Execute MySQL query
#       community.mysql.mysql_query:
#         login_user: "{{ mysql_user }}"
#         login_password: "{{ mysql_password }}"
#         login_host: "{{ mysql_host }}"
#         login_db: "{{ mysql_database }}"
#         query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
#       register: query_result

#     - name: Print the query result
#       debug:
#         var: query_result.query_result

---
- name: Execute MySQL Query
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

    - name: Store query result in host-specific variable
      set_fact:
        host_query_result: "{{ query_result.query_result }}"

  # This task runs only once and aggregates results from all hosts
  - name: Aggregate all query results
    run_once: true
    gather_facts: false
    tasks:
      - name: Combine all query results into a single list
        set_fact:
          aggregated_results: >-
            {{
              hostvars | dict2items |
              map(attribute='value.host_query_result') |
              select('defined') |
              list
            }}

      - name: Print the combined query results
        debug:
          var: aggregated_results
