---
- name: Execute MySQL Query
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

- name: Aggregate and Print Results
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Combine results from all hosts
      set_fact:
        query_results_from_all_hosts: >-
          {{
            groups['all'] | map('extract', hostvars, 'query_result') | select('defined') | map(attribute='query_result') | list
          }}

    - name: Add query result to global aggregated results
      set_fact:
        aggregated_results: "{{ query_results_from_all_hosts }}"

    - name: Print aggregated results
      debug:
        var: aggregated_results

