# ---
# - name: Execute MySQL Query
#   hosts: all
#   gather_facts: false

#   tasks:
#     - name: Execute MySQL query
#       community.mysql.mysql_query:
#         login_user: "{{ mysql_user }}"
#         login_password: "{{ mysql_password }}"
#         login_host: "{{ mysql_host }}"
#         login_db: "{{ mysql_database }}"
#         query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
#       register: query_result

#     - name: Print the query result
#       debug:
#         var: query_result.query_result

---
- name: Execute MySQL Query
  hosts: all
  gather_facts: false

  tasks:
    - name: Initialize results list
      set_fact:
        results_list: []
      run_once: true  # Ensure this runs only once

    - name: Execute MySQL query
      community.mysql.mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT s.oid as station, c.name as number, c.ip, c.url FROM stations s INNER JOIN channels c ON s.id = c.station;"
      register: query_result

    - name: Append query result to results list
      set_fact:
        results_list: "{{ results_list + [query_result.query_result] }}"
      run_once: true  # Ensure this runs only once

    - name: Aggregate results from all hosts
      set_fact:
        aggregated_results: "{{ aggregated_results | default([]) + [query_result.query_result] }}"
      run_once: true  # Ensure this runs only once

    - name: Print the aggregated query results
      debug:
        var: aggregated_results
      run_once: true  # Ensure this runs only once