- name: Install Python and Run Hello World Script
  hosts: all
  tasks:
    - name: Copy Script to machine
      copy:
        src: /etc/scripts/hello_world.py
        dest: /tmp/hello_world.py
        
    - name: Run Hello World Python script
      command: /opt/conda/bin/python /tmp/hello_world.py
      register: script_output

    - debug:
        var: script_output.stdout
