- name: Install Python and Run Hello World Script
  hosts: all
  tasks:
    - name: Run Hello World Python script
      command: /opt/conda/bin/python /tmp/scripts/hello_world.py
      register: script_output

    - debug:
        var: script_output.stdout
